python Chambergo/Simple1.py "pastillas" 18
python Chambergo/Simple1.py "pastillas" 19
python Chambergo/Simple1.py "pastillas" 14

python Chambergo/Simple2.py "usuario1" 13
python Chambergo/Simple2.py "usuario2" 14
python Chambergo/Simple2.py "usuario3" 16

python Chambergo/Simple3.py "alumno1" 5
python Chambergo/Simple3.py "alumno2" 8
python Chambergo/Simple3.py "alumno3" 7

python Chambergo/Simple4.py "cartera" 220
python Chambergo/Simple4.py "casaca" 280
python Chambergo/Simple4.py "botas" 350

python Chambergo/Simple5.py "Pedro" 4
python Chambergo/Simple5.py "Juan" 7
python Chambergo/Simple5.py "Cesar" 9

python Chambergo/Simple6.py "cliente1" 35
python Chambergo/Simple6.py "cliente2" 85
python Chambergo/Simple6.py "cliente3" 76

python Chambergo/Simple7.py "alumno1" 15
python Chambergo/Simple7.py "alumno2" 14
python Chambergo/Simple7.py "alumno3" 13

python Chambergo/Simple8.py "trabajador1" 42
python Chambergo/Simple8.py "trabajador2" 42
python Chambergo/Simple8.py "trabajador3" 40

python Chambergo/Simple9.py "Julio" 42
python Chambergo/Simple9.py "Andres" 65
python Chambergo/Simple9.py "Sandra" 35

python Chambergo/Simple10.py "cliente01" 53
python Chambergo/Simple10.py "cliente02" 48
python Chambergo/Simple10.py "cliente03" 57

python Chambergo/Doble1.py "pastillas" 13
python Chambergo/Doble1.py "pastillas" 10
python Chambergo/Doble1.py "pastillas" 9

python Chambergo/Doble2.py "usuario01" 10
python Chambergo/Doble2.py "usuario02" 8
python Chambergo/Doble2.py "usuario03" 6

python Chambergo/Doble3.py "alumno01" 9
python Chambergo/Doble3.py "alumno01" 4
python Chambergo/Doble3.py "alumno01" 8

python Chambergo/Doble4.py "cartera" 150
python Chambergo/Doble4.py "casaca" 220
python Chambergo/Doble4.py "botas" 180

python Chambergo/Doble5.py "Percy" 5
python Chambergo/Doble5.py "Javier" 3
python Chambergo/Doble5.py "Cecilio" 6

python Chambergo/Doble6.py "cliente01" 65
python Chambergo/Doble6.py "cliente02" 35
python Chambergo/Doble6.py "cliente03" 43

python Chambergo/Doble7.py "alumno01" 11
python Chambergo/Doble7.py "alumno02" 12
python Chambergo/Doble7.py "alumno03" 15

python Chambergo/Doble8.py "trabajador01" 35
python Chambergo/Doble8.py "trabajador02" 26
python Chambergo/Doble8.py "trabajador03" 45

python Chambergo/Doble9.py "Juanes" 23
python Chambergo/Doble9.py "Andrea" 44
python Chambergo/Doble9.py "Sandy" 32

python Chambergo/Doble10.py "cliente1" 24
python Chambergo/Doble10.py "cliente2" 15
python Chambergo/Doble10.py "cliente3" 56

python Chambergo/Multiple1.py "pastillas" 6 3 2
python Chambergo/Multiple1.py "pastillas" 7 4 3
python Chambergo/Multiple1.py "pastillas" 8 5 3

python Chambergo/Multiple2.py "usuario1" 13 9 5
python Chambergo/Multiple2.py "usuario2" 11 7 4
python Chambergo/Multiple2.py "usuario3" 10 8 6

python Chambergo/Multiple3.py "alumno1" 26 18 9
python Chambergo/Multiple3.py "alumno2" 25 19 11
python Chambergo/Multiple3.py "alumno3" 24 20 11

python Chambergo/Multiple4.py "cartera" 350 200 78
python Chambergo/Multiple4.py "casaca" 290 180 80
python Chambergo/Multiple4.py "botas" 250 240 65

python Chambergo/Multiple5.py "Juliana" 10 5 1
python Chambergo/Multiple5.py "Karlos" 15 7 2
python Chambergo/Multiple5.py "Jesus" 9 8 1

python Chambergo/Multiple6.py "cliente1" 550 280 100
python Chambergo/Multiple6.py "cliente2" 500 305 98
python Chambergo/Multiple6.py "cliente3" 480 224 76

python Chambergo/Multiple7.py "alumno1" 15 12 9
python Chambergo/Multiple7.py "alumno2" 14 13 10
python Chambergo/Multiple7.py "alumno3" 13 14 11

python Chambergo/Multiple8.py "Juliana" 45 35 28
python Chambergo/Multiple8.py "Karlos" 40 30 30
python Chambergo/Multiple8.py "Jesus" 50 45 36

python Chambergo/Multiple9.py "trabajador1" 61 32 9
python Chambergo/Multiple9.py "trabajador2" 59 29 4
python Chambergo/Multiple9.py "trabajador3" 45 34 10

python Chambergo/Multiple10.py "cliente01" 55 15 7
python Chambergo/Multiple10.py "cliente02" 50 30 10
python Chambergo/Multiple10.py "cliente03" 48 29 6

python Vilchez/simple01.py "zapatillas" 500
python Vilchez/simple01.py "cartera" 200
python Vilchez/simple01.py "sandalias" 400


python Vilchez/simple02.py "Alicia" 28 50 10
python Vilchez/simple02.py "Patrick" 28 75 10
python Vilchez/simple02.py "Keyla" 27 65 5


python Vilchez/simple03.py "Rita" 2
python Vilchez/simple03.py "Carlos" 4
python Vilchez/simple03.py "Jose" 5


python Vilchez/simple04.py "Karla" 15 12 18 11
python Vilchez/simple04.py "Kevin" 11 15 17 16
python Vilchez/simple04.py "Guadalupe" 18 20 15 16


python Vilchez/simple05.py "Axel" "pantalones"  4 80
python Vilchez/simple05.py "Santiago" "zapatillas" 2 350
python Vilchez/simple05.py "Diego" "tv" 1 1800

python Vilchez/simple06.py "Valentin" "Doctor" 38 "24meses"
python Vilchez/simple06.py "Luis" "Ingeniero de sitemas" 27 "6meses"
python Vilchez/simple06.py "Sergio" "Contador" 35 "12meses"

python Vilchez/simple07.py "Lidia" "Particular" 49 "Si"
python Vilchez/simple07.py "Antonio" "Particular" 55 "Si"
python Vilchez/simple07.py "Elena" "Seguro" 38 "No"

python Vilchez/simple08.py "Juana" 2019 1996
python Vilchez/simple08.py "Tomas" 2019 1987
python Vilchez/simple08.py "Angie" 2019 2002

python Vilchez/simple09.py "Andre" "Coronel de la Marina" 100 6
python Vilchez/simple09.py "Monica" "Jefa de mantenimiento" 50 4
python Vilchez/simple09.py "Arsenio" "SubGeneral" 80 7


python Vilchez/simple10.py "Josefina" 180 150
python Vilchez/simple10.py "Eduardo" 100 100
python Vilchez/simple10.py "Blanca" 50 80

python Vilchez/condicionales.dobles11.py "zapatillas" 350
python Vilchez/condicionales.dobles11.py "zapatillas" 150
python Vilchez/condicionales.dobles11.py "cartera Renzo Costa" 500

python Vilchez/condicionales.dobles12.py "Alicia" 28 50 10
python Vilchez/condicionales.dobles12.py "Patrick" 28 75 10
python Vilchez/condicionales.dobles12.py "Keyla" 27 50 5

python Vilchez/condicionales.dobles.13.py "Rita" 6
python Vilchez/condicionales.dobles.13.py "Carlos" 4
python Vilchez/condicionales.dobles.13.py "Jose" 8

python Vilchez/condicionales.dobles14.py "Karla" 15 12 11 12
python Vilchez/condicionales.dobles14.py "Kevin" 11 15 14 16
python Vilchez/condicionales.dobles14.py "Guadalupe" 18 20 15 16

python Vilchez/condicionales.dobles15.py "Axel" "pantalones"  4 80
python Vilchez/condicionales.dobles15.py "Santiago" "zapatillas" 2 350
python Vilchez/condicionales.dobles15.py "Diego" "polos" 2 80

python Vilchez/condicionales.dobles16.py "Valentin" "Doctor" 38 "24meses"
python Vilchez/condicionales.dobles16.py "Luis" "Ingeniero de sitemas" 27 "6meses"
python Vilchez/condicionales.dobles16.py "Sergio" "Contador" 35 "12meses"

python Vilchez/condicionales.dobles17.py "Lidia" "Particular" 49 "Si"
python Vilchez/condicionales.dobles17.py "Antonio" "Seguro" 55 "No"
python Vilchez/condicionales.dobles17.py "Elena" "Seguro" 38 "No"

python Vilchez/condicionales.dobles18.py "Juana" 2019 1996
python Vilchez/condicionales.dobles18.py "Tomas" 2019 2005
python Vilchez/condicionales.dobles18.py "Angie" 2019 2002

python Vilchez/condicionales.dobles19.py "Andre" "Coronel de la Marina" 100 6
python Vilchez/condicionales.dobles19.py "Monica" "Jefa de mantenimiento" 50 4
python Vilchez/condicionales.dobles19.py "Arsenio" "SubGeneral" 80 7

python Vilchez/condicionales.dobles20.py "Josefina" 180 150
python Vilchez/condicionales.dobles20.py "Eduardo" 100 100
python Vilchez/condicionales.dobles20.py "Blanca" 50 80

python Vilchez/condicionales.multiples21.py "zapatillas" 350
python Vilchez/condicionales.multiples21.py "zapatillas" 220
python Vilchez/condicionales.multiples21.py "cartera Renzo Costa" 95

python Vilchez/condicionales.multiples22.py "Alicia" 28 60 10
python Vilchez/condicionales.multiples22.py "Patrick" 26 50 5
python Vilchez/condicionales.multiples22.py "Keyla" 23 30 6


python Vilchez/condicionales.multiples23.py "Rita" 7
python Vilchez/condicionales.multiples23.py "Carlos" 5
python Vilchez/condicionales.multiples23.py "Jose" 3

python Vilchez/condicionales.multiples24.py "Karla" 20 18 19 20
python Vilchez/condicionales.multiples24.py "Kevin" 17 16 15 16
python Vilchez/condicionales.multiples24.py "Guadalupe" 12 11 11 10

python Vilchez/condicionales.multiples25.py "Axel" "pantalones" 6 80
python Vilchez/condicionales.multiples25.py "Santiago" "zapatillas" 1 280
python Vilchez/condicionales.multiples25.py "Diego" "polos" 1 60

python Vilchez/condicionales.multiples26.py "Valentin" "Doctor" 38 "24meses"
python Vilchez/condicionales.multiples26.py "Luis" "abogado" 27 "18meses"
python Vilchez/condicionales.multiples26.py "Sergio" "contador" 35 "14meses"

python Vilchez/condicionales.multiples27.py "Lidia" "Particular" 49 "Si"
python Vilchez/condicionales.multiples27.py "Antonio" "SIS" 55 "No"
python Vilchez/condicionales.multiples27.py "Elena" "ESsalud" 38 "Si"

python Vilchez/condicionales.multiples28.py "Juana" 2019 1996
python Vilchez/condicionales.multiples28.py "Tomas" 2019 2018
python Vilchez/condicionales.multiples28.py "Angie" 2019 2005

python Vilchez/condicionales.multiples29.py "Andre" "Coronel de la Marina" 100 6
python Vilchez/condicionales.multiples29.py "Monica" "Jefa de mantenimiento" 135 7
python Vilchez/condicionales.multiples29.py "Arsenio" "SubGeneral" 0 0

python Vilchez/condicionales.multiples30.py "Josefina" 180 300
python Vilchez/condicionales.multiples30.py "Eduardo" 100 100
python Vilchez/condicionales.multiples30.py "Blanca" 50 110

















